title: "Sam's Blog"
author: "Sam"
description: "Ethical hacking, cybersecurity tools, and real-world learningâ€”documented with clarity and purpose."

email: "samerwleeed@gmail.com"
twitter_username: "sam_x86_"
github_username: "samx-86"
youtube_username: "hack_scale"

theme: minima
rss: rss

plugins:
  - jekyll-feed
  - jekyll-sitemap
