title: "Sam's Blog"
author: "Sam"
description: "Cybersecurity, ethical hacking, and the hacker mindset. Practical learning without hype."

email: "samerwleeed@mail.com"
twitter_username: "sam_x86_"
github_username: "samx-86"
youtube_username: "hack_scale"

theme: minima
rss: rss

plugins:
  - jekyll-feed
  - jekyll-sitemap
